### ISSUE TITLE
One City Challenge game option is not working properly - AIs can place more than one city.

### ISSUE THREAD

**Issue by raxo2222** [caveman2cosmos/Caveman2Cosmos#355] opened 2020-01-09 19:25 UTC
It needs further refinement too - disabling requirements related to amount of cities.
Resource in vicinity requirement could be forced to be normal requirement too.

https://forums.civfanatics.com/threads/forced-one-city-civs-for-every-player.653637/#post-15638190

**Comment by WilsonCA** [comment] 2020-03-28 21:36
This is not an issue. It is as designed. 
OCC is, and always has been, a 'challenge' for just the human player. Civ4 only limits the player to one city, and intentionally allows the AI to grab as much as they want. Limiting the AI to only one city would not be a challenge at all. It is in fact the bonus to happy/healthy/growth/maintenance that makes higher difficulties actually difficult. Limiting the AI to one city was never an intended play style. 
Now, if someone wants the AI to have the same restriction with same bonuses to building prerequisites (apparently yes, in the referenced thread), that could probably be created as a completely new game option... but so much work for so little gameplay value seems a poor use of dev resources, if I were PM here (no one is, you guys do you and have fun). Seems so much easier to just modmod, remove the settler unit, and create an event that triggers when you have 2 cities (through capture) that does whatever you want it to. But I suggest closing this issue and the referenced thread. A source: https://www.civfanatics.com/civ4/strategy/peacemonger/beginners-guide-to-one-city-challenge-occ/

**Closed** 2020-03-28 21:37 UTC
Labels: bug, dll
